// Generated by dts-bundle-generator v9.5.1

export declare function transformVue(input: string): string;
export declare function isLimSFC(input: string, filename?: string): boolean;
declare const _default: {
	transformVue: typeof transformVue;
	isLimSFC: typeof isLimSFC;
};

export {
	_default as default,
};

export {};
