// Generated by dts-bundle-generator v9.5.1

export declare function transformReact(input: string): string;
export declare function isLimReact(input: string, filename?: string): boolean;
declare const _default: {
	transformReact: typeof transformReact;
	isLimReact: typeof isLimReact;
};

export {
	_default as default,
};

export {};
